//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjYiFaShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tAdmin
    {
        public int fId { get; set; }
        [DisplayName("管理者帳號")]
        public string fAdminId { get; set; }
        [DisplayName("管理者密碼")]
        public string fPwd { get; set; }
        [DisplayName("管理者姓名")]
        public string fName { get; set; }
    }
}
